-- StudyCore — Supabase schema (Checkpoint 1). لم يُنفَّذ على مشروع حقيقي؛ شغّله من SQL Editor.
-- ملاحظة: اسم العمود order محجوز في SQL، لذلك استُخدم sort_order (يُحوَّل إلى order في الكود).

create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  term_id bigint not null references public.terms(id) on delete cascade,
  name text not null,
  icon text not null default 'book',
  sort_order int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (term_id, name)
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  name text not null,
  icon text not null default 'book',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_id, name)
);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  section_id bigint not null references public.sections(id) on delete cascade,
  name text not null,
  type text not null check (type in ('pdf','video','link')),
  url text not null,
  drive_url text,               -- جاهز لربط Google Drive لاحقًا (غير مستخدم الآن)
  sort_order int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subjects_term_order_idx on public.subjects (term_id, sort_order);
create index if not exists sections_subject_order_idx on public.sections (subject_id, sort_order);
create index if not exists content_section_order_idx on public.content_items (section_id, sort_order);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$ declare t text; begin
  foreach t in array array['terms','subjects','sections','content_items'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- الأدمن: جدول صغير بدل "أي مستخدم مسجّل". role جاهز لأدوار مستقبلية (الآن: admin فقط).
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid())
$$;

alter table public.terms enable row level security;
alter table public.subjects enable row level security;
alter table public.sections enable row level security;
alter table public.content_items enable row level security;
alter table public.admin_users enable row level security;

-- القراءة العامة (الطلاب بدون تسجيل): المنشور فقط. الأدمن يرى كل شيء.
drop policy if exists "read terms" on public.terms;
create policy "read terms" on public.terms for select using (true);
drop policy if exists "read subjects" on public.subjects;
create policy "read subjects" on public.subjects for select using (is_published or public.is_admin());
drop policy if exists "read sections" on public.sections;
create policy "read sections" on public.sections for select using (true);
drop policy if exists "read content" on public.content_items;
create policy "read content" on public.content_items for select using (is_published or public.is_admin());

-- الكتابة: الأدمن فقط
do $$ declare t text; begin
  foreach t in array array['terms','subjects','sections','content_items'] loop
    execute format('drop policy if exists "admin write %1$s" on public.%1$I', t);
    execute format('create policy "admin write %1$s" on public.%1$I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "own admin row" on public.admin_users;
create policy "own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());
-- لا توجد سياسات كتابة على admin_users: أضف الأدمن من SQL Editor فقط (انظر README).
