-- StudyCore setup.sql = schema.sql + seed.sql (للصق مرة واحدة في Supabase SQL Editor). آمن لإعادة التشغيل.

-- StudyCore — Supabase schema (Checkpoint 1). لم يُنفَّذ على مشروع حقيقي؛ شغّله من SQL Editor.
-- ملاحظة: اسم العمود order محجوز في SQL، لذلك استُخدم sort_order (يُحوَّل إلى order في الكود).

create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  term_id bigint not null references public.terms(id) on delete cascade,
  name text not null,
  icon text not null default 'book',
  sort_order int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (term_id, name)
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  name text not null,
  icon text not null default 'book',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_id, name)
);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  section_id bigint not null references public.sections(id) on delete cascade,
  name text not null,
  type text not null check (type in ('pdf','video','link')),
  url text not null,
  drive_url text,               -- رابط Google Drive الموحّد (لعناصر pdf)
  drive_file_id text,           -- معرّف الملف المستخرج من الرابط
  sort_order int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_pdf_has_drive check (type <> 'pdf' or drive_file_id is not null)
);

create index if not exists subjects_term_order_idx on public.subjects (term_id, sort_order);
create index if not exists sections_subject_order_idx on public.sections (subject_id, sort_order);
create index if not exists content_section_order_idx on public.content_items (section_id, sort_order);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

do $$ declare t text; begin
  foreach t in array array['terms','subjects','sections','content_items'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- الأدمن: جدول صغير بدل "أي مستخدم مسجّل". role جاهز لأدوار مستقبلية (الآن: admin فقط).
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid())
$$;

alter table public.terms enable row level security;
alter table public.subjects enable row level security;
alter table public.sections enable row level security;
alter table public.content_items enable row level security;
alter table public.admin_users enable row level security;

-- القراءة العامة (الطلاب بدون تسجيل): المنشور فقط، ولا يظهر شيء داخل مادة مخفية. الأدمن يرى كل شيء.
drop policy if exists "read terms" on public.terms;
create policy "read terms" on public.terms for select using (true);
drop policy if exists "read subjects" on public.subjects;
create policy "read subjects" on public.subjects for select using (is_published or public.is_admin());
drop policy if exists "read sections" on public.sections;
create policy "read sections" on public.sections for select using (
  public.is_admin() or exists (select 1 from public.subjects j where j.id = subject_id and j.is_published)
);
drop policy if exists "read content" on public.content_items;
create policy "read content" on public.content_items for select using (
  public.is_admin() or (
    is_published and exists (
      select 1 from public.sections x join public.subjects j on j.id = x.subject_id
      where x.id = section_id and j.is_published
    )
  )
);

-- الكتابة: الأدمن فقط
do $$ declare t text; begin
  foreach t in array array['terms','subjects','sections','content_items'] loop
    execute format('drop policy if exists "admin write %1$s" on public.%1$I', t);
    execute format('create policy "admin write %1$s" on public.%1$I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "own admin row" on public.admin_users;
create policy "own admin row" on public.admin_users for select to authenticated using (user_id = auth.uid());
-- لا توجد سياسات كتابة على admin_users: أضف الأدمن من SQL Editor فقط (انظر README).

-- StudyCore seed: نفس بيانات data/catalog.ts. آمن لإعادة التشغيل (on conflict do nothing).
-- المادة السابعة في الترم الثاني غير معرّفة بعد ولذلك غير موجودة.
insert into public.terms (id,name,sort_order) values
  (1,'الترم الأول',1),
  (2,'الترم الثاني',2)
on conflict do nothing;

insert into public.subjects (id,term_id,name,icon,sort_order) values
  (1,1,'English','lang',1),
  (2,1,'E-commerce','cart',2),
  (3,1,'CS','code',3),
  (4,1,'Physics','atom',4),
  (5,1,'Math 1','sigma',5),
  (6,1,'Math 0','calc',6),
  (7,1,'Ethics','scale',7),
  (8,2,'Electronics','bolt',1),
  (9,2,'Introduction to Artificial Intelligence','spark',2),
  (10,2,'Discrete Mathematics','sigma',3),
  (11,2,'Digital Logic Design','logic',4),
  (12,2,'Introduction to Cyber Security','shield',5),
  (13,2,'Computer Programming & Problem Solving','code',6)
on conflict do nothing;

insert into public.sections (id,subject_id,name,icon,sort_order) values
  (1,1,'كتاب الجامعة','book',1),
  (2,1,'المحاضرات','lec',2),
  (3,1,'السكاشن','sec',3),
  (4,1,'الملخصات','sum',4),
  (5,1,'الفيديوهات','vid',5),
  (6,1,'الأسئلة','q',6),
  (7,1,'الامتحانات','ex',7),
  (8,2,'كتاب الجامعة','book',1),
  (9,2,'المحاضرات','lec',2),
  (10,2,'السكاشن','sec',3),
  (11,2,'الملخصات','sum',4),
  (12,2,'الفيديوهات','vid',5),
  (13,2,'الأسئلة','q',6),
  (14,2,'الامتحانات','ex',7),
  (15,3,'كتاب الجامعة','book',1),
  (16,3,'المحاضرات','lec',2),
  (17,3,'السكاشن','sec',3),
  (18,3,'الملخصات','sum',4),
  (19,3,'الفيديوهات','vid',5),
  (20,3,'الأسئلة','q',6),
  (21,3,'الامتحانات','ex',7),
  (22,4,'كتاب الجامعة','book',1),
  (23,4,'المحاضرات','lec',2),
  (24,4,'السكاشن','sec',3),
  (25,4,'الملخصات','sum',4),
  (26,4,'الفيديوهات','vid',5),
  (27,4,'الأسئلة','q',6),
  (28,4,'الامتحانات','ex',7),
  (29,5,'كتاب الجامعة','book',1),
  (30,5,'المحاضرات','lec',2),
  (31,5,'السكاشن','sec',3),
  (32,5,'الملخصات','sum',4),
  (33,5,'الفيديوهات','vid',5),
  (34,5,'الأسئلة','q',6),
  (35,5,'الامتحانات','ex',7),
  (36,6,'كتاب الجامعة','book',1),
  (37,6,'المحاضرات','lec',2),
  (38,6,'السكاشن','sec',3),
  (39,6,'الملخصات','sum',4),
  (40,6,'الفيديوهات','vid',5),
  (41,6,'الأسئلة','q',6),
  (42,6,'الامتحانات','ex',7),
  (43,7,'كتاب الجامعة','book',1),
  (44,7,'المحاضرات','lec',2),
  (45,7,'السكاشن','sec',3),
  (46,7,'الملخصات','sum',4),
  (47,7,'الفيديوهات','vid',5),
  (48,7,'الأسئلة','q',6),
  (49,7,'الامتحانات','ex',7),
  (50,8,'كتاب الجامعة','book',1),
  (51,8,'المحاضرات','lec',2),
  (52,8,'السكاشن','sec',3),
  (53,8,'الملخصات','sum',4),
  (54,8,'الفيديوهات','vid',5),
  (55,8,'الأسئلة','q',6),
  (56,8,'الامتحانات','ex',7),
  (57,9,'كتاب الجامعة','book',1),
  (58,9,'المحاضرات','lec',2),
  (59,9,'السكاشن','sec',3),
  (60,9,'الملخصات','sum',4),
  (61,9,'الفيديوهات','vid',5),
  (62,9,'الأسئلة','q',6),
  (63,9,'الامتحانات','ex',7),
  (64,10,'كتاب الجامعة','book',1),
  (65,10,'المحاضرات','lec',2),
  (66,10,'السكاشن','sec',3),
  (67,10,'الملخصات','sum',4),
  (68,10,'الفيديوهات','vid',5),
  (69,10,'الأسئلة','q',6),
  (70,10,'الامتحانات','ex',7),
  (71,11,'كتاب الجامعة','book',1),
  (72,11,'المحاضرات','lec',2),
  (73,11,'السكاشن','sec',3),
  (74,11,'الملخصات','sum',4),
  (75,11,'الفيديوهات','vid',5),
  (76,11,'الأسئلة','q',6),
  (77,11,'الامتحانات','ex',7),
  (78,12,'كتاب الجامعة','book',1),
  (79,12,'المحاضرات','lec',2),
  (80,12,'السكاشن','sec',3),
  (81,12,'الملخصات','sum',4),
  (82,12,'الفيديوهات','vid',5),
  (83,12,'الأسئلة','q',6),
  (84,12,'الامتحانات','ex',7),
  (85,13,'كتاب الجامعة','book',1),
  (86,13,'المحاضرات','lec',2),
  (87,13,'السكاشن','sec',3),
  (88,13,'الملخصات','sum',4),
  (89,13,'الفيديوهات','vid',5),
  (90,13,'الأسئلة','q',6),
  (91,13,'الامتحانات','ex',7)
on conflict do nothing;

select setval(pg_get_serial_sequence('public.terms','id'), (select max(id) from public.terms));
select setval(pg_get_serial_sequence('public.subjects','id'), (select max(id) from public.subjects));
select setval(pg_get_serial_sequence('public.sections','id'), (select max(id) from public.sections));
